apiVersion: v1
kind: ReplicationController
metadata:
  name: route53-kubernetes
  namespace: kube-system
  labels:
    app: route53-kubernetes
spec:
  replicas: 1
  selector:
    app: route53-kubernetes
  template:
    metadata:
      labels:
        app: route53-kubernetes
    spec:
      volumes:
        - name: ssl-cert
          hostPath:
            path: "/etc/kubernetes"
      containers:
        - image: camil/route53-kubernetes:v1
          imagePullPolicy: Always
          name: route53-kubernetes
          volumeMounts:
            - name: ssl-cert
              mountPath: /etc/kubernetes
              readOnly: true
          env:
            - name: "CA_FILE_PATH"
              value: "/etc/kubernetes/ssl/ca.pem"
            - name: "CERT_FILE_PATH"
              value: "/etc/kubernetes/ssl/worker.pem"
            - name: "KEY_FILE_PATH"
              value: "/etc/kubernetes/ssl/worker-key.pem"
            - name : "AWS_REGION"
              value: "us-east-1"
